FROM golang:1.16

WORKDIR /usr/src/app

COPY . .

RUN go build

ENV PORT=8080 REQUEST_ORIGIN=http://localhost:5000

CMD ["./server"]

# docker build . -t backend-example && docker run -p 8080:8080 backend-example