FROM node:16-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN REACT_APP_BACKEND_URL=http://localhost:8080 npm run build

EXPOSE 5000

RUN npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]

# docker build . -t frontend-example && docker run -p 5000:5000 frontend-example