version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile

  redis:
    image: redis:alpine

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
